#include "Config.h"

bool GARBAGE_MEMORY = false;
bool SINGLE_STATE_MODE = false;
bool IGNORE_UNINITIALIZED_MEM = true;

byte CLOCK_PERIOD_MILLIS = 1;
clock_time CYCLES_LIMIT = 5000;

byte IC_CYCLES_PER_OP = 3;
byte IC_CYCLES_PER_OP_WITH_CACHE_HIT = 2;
byte LS_CYCLES_PER_OP = 15;
byte LS_CYCLES_PER_OP_WITH_CACHE_HIT = 7;
byte DE_CYCLES_PER_OP = 2;
byte EX_CYCLES_PER_OP = 5;

word IC_CACHE_WORDS_SIZE = 64;
word LS_CACHE_WORDS_SIZE = 64;
byte LS_CACHE_SET_ENTRIES_COUNT = 2;
